# Generated by Django 3.0.1 on 2020-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Eng', 'English'), ('datastruct', 'Datastructure'), ('Programing', 'Programming'), ('Comp', 'Computer')], default=None, max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('A', models.CharField(max_length=255)),
                ('B', models.CharField(max_length=255)),
                ('C', models.CharField(max_length=255)),
                ('D', models.CharField(max_length=255)),
                ('answer_correct', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
