# Generated by Django 3.0.1 on 2020-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
