# Generated by Django 3.0.1 on 2020-01-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
