# Generated by Django 3.0.1 on 2020-01-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0003_auto_20200103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
