# Generated by Django 3.0.1 on 2020-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0004_auto_20200103_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='interest',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
