# Generated by Django 3.0.1 on 2020-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0006_auto_20200106_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='education',
            field=models.CharField(choices=[('Matric', 'Matric'), ('Intermediate', 'Intermediate'), ('Diploma', 'Diploma'), ('Master', 'Master'), ('PHD', 'PHD')], max_length=100),
        ),
    ]
