# Generated by Django 3.0.1 on 2020-01-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0007_auto_20200106_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Registerations',
        ),
    ]
