# Generated by Django 3.0.1 on 2020-01-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0008_auto_20200106_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileedit',
            name='registerations_form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bestfit.Registerations'),
        ),
    ]
