# Generated by Django 3.0.1 on 2020-01-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestfit', '0009_profileedit_registerations_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileedit',
            name='address',
        ),
        migrations.AddField(
            model_name='profileedit',
            name='address_1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profileedit',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
